### ISSUE TITLE
Totem buttons not appearing while playing on phone 

### ISSUE THREAD

**Issue by MuralovTY** [YellowCat98/TotemofUndying-gd#1]
And I also recommend the possibility of customizing the totem (I have a lot of totems :3)

**Comment by MuralovTY** [comment]
If anything, the penalty has this function enabled

**Comment by Asterveila** [comment]
Totem button seems to be off by default on mobile rn, check the mod's settings and enable it

**Comment by MuralovTY** [comment]
Yes, it was initially disabled, but when I turned it on, nothing changed

**Comment by Asterveila** [comment]
oooh okay, was just sayin cuz i just tested and it worked for me

**Comment by Helloausername** [comment]
> Yes, it was initially disabled, but when I turned it on, nothing changed
Try changing it from the mod's save file settings

**Comment by MuralovTY** [comment]
> > Yes, it was initially disabled, but when I turned it on, nothing changed
> > Try changing it from the mod's save file settings

It says True

**Comment by MuralovTY** [comment]
I was able to fix it. For some reason the mod does not require Node IDs and because of this the mod does not work. (I am just a mod reviewer in telegram and I remove all mods every time)

**Comment by MuralovTY** [comment]
I was able to fix it. For some reason the mod does not require Node IDs and because of this the mod does not work. (I am just a mod reviewer in telegram and I remove all mods every time)

**Comment by MuralovTY** [comment]
It remains to understand how it works. Just pressing the button does not work)

**Comment by Asterveila** [comment]
Make sure to beat at least 1 rated level with the mod on, u can't just use it u need to get totems first (which u get by acquiring stars, 5 stars = 5 totems, 9 stars = 9 totems and so on)

**Comment by MuralovTY** [comment]
Got it, thanks for your help :3
