### ISSUE TITLE
Totem button on top of pause and one more issuem

### ISSUE THREAD

**Issue by ghost** [YellowCat98/TotemofUndying-gd#3]
When pressing the totem button, it opens up the pause menu. 

Sometimes, the totems wouldn't work and would shake the screen, even though I haven't used the totem in that run.

**Comment by Asterveila** [comment]
the screen shake means you ran out of totems, your totem count is global, meaning you can have, say, 5 totems and use 3 in one run and the remaining 2 in another, or all 5 in one, it isn't a "one totem per run" mechanic but rather a global stat
